### ISSUE TITLE
Create migration for app_configs table

### ISSUE THREAD

**Issue by hamidsultanzadeh** [webperside/course-erp-backend#21]
The table will have the following columns:
key (varchar), value (varchar), description (varchar), is_deleted

The migration file name should be 1.x.x-app-configs-table.xml

Source branch: main

**Comment by aytiqaqash** [comment]
Based on the tasks' order #20 will have a file name "1.1.1-alter-languages-table.xml". I believe your file name will be "1.1.2-app-configs-table.xml"
