### ISSUE TITLE
Add / edit endpoint for country

### ISSUE THREAD

**Issue by hamidsultanzadeh** [webperside/course-erp-backend#30]
Endpoint: POST /v1/countries
Fields: (comes from FRONT)
- name

Flow:
Take data, and insert it

Validations:
SKIP for now

Endpoint: PUT /v1/countries/{id}
Fields: (comes from FRONT)
- name

Flow:
Take data, and update it

Validations:
SKIP for now

Note:
You don't need to check whether this id is exist or not. Because we'll follow more reusable way for that

**USE BUSINESS SERVICE LAYER**
**USE MapStruct for mapping process**

**Comment by aytiqaqash** [comment]
Hi @hamidsultanzadeh and @farhadnajafov, could you please move this ticket to the testing when it is ready for?
