### ISSUE TITLE
Make return 201 created for POST resource creation endpoints

### ISSUE THREAD

**Issue by hamidsultanzadeh** [webperside/course-erp-backend#45]
make the endpoints that have add logic return 201
create a new method inside BaseResponse named created()

**Comment by aytiqaqash** [comment]
I have changed the title from specific to POST resource creation, I hope it is fine. Please revert back if you didn't mean that.

**Comment by hamidsultanzadeh** [comment]
@aytiqaqash , looks good. thanks
