### ISSUE TITLE
[INVESTIGATION] All small issues on backend

### ISSUE THREAD

**Issue by hamidsultanzadeh** [webperside/course-erp-backend#56]
please leave your comments when you get new issues

**Comment by gadirovakhadija** [comment]
At the SubjectMapper b.is_deleted must be s.is_deleted inside the sql tags.
At the SubjectPayload variables' access level must be private.
At the SubjectBusinessServiceImpl should be added @Slf4j annotation.

**Comment by ttayping** [comment]
classes which unused import statement exist: 
1. CountryController
2. StudentContoller
3. TestController
4. BaseException
5. GlobalExceptionHandler
6. AuthorizationFilter
7. BaseResponse
8. CountryEntityMapper
9. UserEntityMapper
10. LanguageRepository
11. SubjectRepository
12. CountryService
13. LanguageService
14. EmailOTPServiceImpl
15. OTP Factory
16. RedisService
17. RoleService
18. StudentService

At the TestController missing @RequestMapping annotation.

unnecessary semicolon at models.response.SuccessResponseMessages.

at the CountryPayload we dont need @Setter and @Getter. @Data annotation cover them.

rename LangugaeRepository to LanguageRepository (dont forget to change it at the LanguageMapper.xml).

we can use @FieldDefaults annotation at the service.security.AuthBusinessServieImpl and the service.student.StudentBusinessServiceImpl. 

At the UserDetailServiceImpl.java should be added @slf4j annotation.

why we need @Param annotation in parameter of findById method at repositories?

**Comment by gadirovakhadija** [comment]
Also must be added AccessLevel with @FieldDefauls instead of seperate AccessLevel SubjectBusinessServiceImpl and RoleServiceImpl

**Comment by hamidsultanzadeh** [comment]
@ttayping param annotation belongs to MyBatis. it helps us to refer to a variable in parameter list from SQL. 

I created a new task for you. please fix the issues you mentioned

**Comment by hamidsultanzadeh** [comment]
@gadirovakhadija I didn't get that what do you want to mean?
