### ISSUE TITLE
[FEATURE] Create OTP util methods

### ISSUE THREAD

**Issue by hamidsultanzadeh** [webperside/course-erp-backend#65]
class; OTPUtils 

1. prepareKey method (static), accepts two parameters. String keyTemplate, Object... args. Use String's format() method to format the target string. Returns formatted string. 

f.e; `OTPUtils.prepareKey("OTP_SIGN_UP_%s_%s", user.getId(), user.getPhoneNumber());`

2. isValid method (static), accepts two parameters. String key, String otp. 
For this method, you have to inject RedisService to this class. We did similar example on PrivatePublicKeyUtils class. (injected variable to static field for reaching from static class) 
after injecting RedisSerivce you can fetch the data from redis by the given key, and check the equality of these OTP's. if they are not equal, just throw OTP_IS_NOT_VALID error (you need to create this error on Enum). if they are equals, do nothing

f.e; 
```
OTPUtils.isValid(
     OTPUtils.prepareKey("OTP_SIGN_UP_%s_%s", user.getId(), user.getPhoneNumber()),
     req.getOtp()
)
```

### UPDATE 06.10.23 / 06:00 
Ignore the first method. It is unnecessary to wrap `formatted` method. And also the second given example will be changed 

f.e; 
```
OTPUtils.isValid(
     "OTP_SIGN_UP_%s_%s".formatted(user.getId(), user.getPhoneNumber()),
     req.getOtp()
)
```

### UPDATE 10.10.23 / 01:27

Write unit tests for this class

**Comment by gadirovakhadija** [comment]
Can I add enum for OTP_IS_NOT_VALID  ? @hamidsultanzadeh

**Comment by hamidsultanzadeh** [comment]
Just add NOT VALID on error enum @gadirovakhadija

**Comment by gadirovakhadija** [comment]
I must check class just isNotValid version or also must check valid version of class with test class? Like testIsValidWithValidOTP()  and testIsValidWithInvalidOTP();

**Comment by hamidsultanzadeh** [comment]
Yes @gadirovakhadija
