### ISSUE TITLE
[FEATURE] Create migration file for teachers

### ISSUE THREAD

**Issue by hamidsultanzadeh** [webperside/course-erp-backend#72]
The table will have the following columns:
id, user_id (foreign key to users table), is_deleted

The last version of the migration file is commented on here #58 
name: teachers_table

don't forget to put the last version on #58 

Source branch: main

**Comment by aytiqaqash** [comment]
- [ ] create 1.1.7-create-teachers-table.xml
- [ ] include the file to changelog-1.0.xml
